package org.projectlombok.security.totpexample.servlets;

import java.io.IOException;
import java.io.Writer;
import java.util.HashMap;
import java.util.Map;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.projectlombok.security.totpexample.Session;
import org.projectlombok.security.totpexample.SessionNotFoundException;
import org.projectlombok.security.totpexample.SessionStore;

import freemarker.template.Configuration;
import freemarker.template.Template;
import freemarker.template.TemplateException;

/**
 * This servlet serves up the start of the login process, where a user enters their  username and password.
 * 
 * Submissions to the form generated by this servlet are handled by {@link VerifyTotpServlet}.
 * 
 * It is possible to get here from inside the login process, in case the user runs into an unfixable failure during the process.
 */
public class LoginServlet extends HttpServlet {
	private final Template loginTemplate;
	private final SessionStore sessions;
	
	public LoginServlet(Configuration templates, SessionStore sessions) throws IOException {
		this.loginTemplate = templates.getTemplate("login.html");
		this.sessions = sessions;
	}
	
	@Override protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		String sessionKey = request.getParameter("si");
		String errorMessage = "";
		if (sessionKey != null) {
			try {
				Session session = sessions.get(sessionKey);
				errorMessage = session.getOrDefault("errMsg", "");
			} catch (SessionNotFoundException e) {
				// Treat this as if there is no session.
			}
		}
		
		Map<String, Object> root = new HashMap<>();
		if (!errorMessage.isEmpty()) root.put("errMsg", errorMessage);
		response.setContentType("text/html; charset=UTF-8");
		try (Writer out = response.getWriter()) {
			loginTemplate.process(root, out);
		} catch (TemplateException e) {
			throw new ServletException("Template broken: login.html", e);
		}
	}
}
